### ISSUE TITLE
The script needs PHP version > 5.3.0 to run.

### ISSUE THREAD

**Issue by kostasdizas** [thesquaregroot/php-rsvp#2]
Have you considered adding version checks?

**Comment by thesquaregroot** [comment]
I'll definitely check to see what's involved in supporting at least version 5.2 since it seems to still be used fairly widely.  Is there another earlier version that would you expect to be supported?

**Comment by kostasdizas** [comment]
PHP lists the supported versions in http://php.net/supported-versions.php

I would expect the latest version to be supported, but with checks in place to prevent it from trying to run on unsupported versions, which can produce unexpected results.

**Comment by thesquaregroot** [comment]
Ah, I see. I misunderstood what you were looking for.  I can definitely add in something to warn about using old versions, that's a good idea.

**Comment by thesquaregroot** [comment]
Please take a look at the version_checks branch. It should print warnings for people using unsupported versions as well as version that do not have the password_hash family of functions. Does this cover what you were looking for?

**Comment by thesquaregroot** [comment]
Changes merged into trunk (v0.1.1) and issue closed.
