### ISSUE TITLE
Database setup failing due to class not found

### ISSUE THREAD

**Issue by mrzool** [thesquaregroot/php-rsvp#4]
Hi there, I'm trying out this old and unmaintained, but very interesting package...

The initial database setup is failing because the class `mysqli` cannot be found. Full apache error:

```
PHP Fatal error:  Class 'mysqli' not found in /var/www/[...]/include/db_setup_functions.php on line 133, referer: https://[example.com]/rsvp_admin.php
```

Is this something that is easily fixable? Just to test things out I'm running this on `PHP 5.6.40-63+ubuntu22.04.1`.

Thanks!

**Comment by mrzool** [comment]
Fixed. I was just missing a module :)

**Comment by thesquaregroot** [comment]
Glad you were able to figure it out, I hadn't had a chance to look at this yet.  Feel free to open another issue if you run into any other problems getting things working.

**Comment by mrzool** [comment]
Thanks!
